version: '3.9'

volumes:
  postgres_data_alteasy:
  static_alteasy:
  media_alteasy:

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_alteasy
    volumes:
      - postgres_data_alteasy:/var/lib/postgresql/data/
    env_file:
      - ./.env
#    ports:
#      - "5448:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web_alteasy
    command: bash -c "python3 manage.py collectstatic --noinput && 
                      python3 manage.py migrate && 
                      python3 manage.py loaddata alteasy/fixtures/user.json alteasy/fixtures/profile.json && 
                      python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - static_alteasy:/usr/src/app
      - media_alteasy:/usr/src/app
    env_file:
      - ./.env